DROP TABLE RGMS_DB.Users;

DROP DATABASE RGMS_DB;

CREATE DATABASE RGMS_DB;

CREATE TABLE RGMS_DB.Users (
	Id INT PRIMARY KEY NOT NULL auto_increment,
	FirstName VARCHAR(64),
	LastName VARCHAR(64),
	Username VARCHAR(64) NOT NULL UNIQUE,
	Passphrase VARCHAR(64)NOT NULL,
	ImageReference VARCHAR(512)
);