DROP TABLE RGMS_DB.Meetings;
DROP TABLE RGMS_DB.Users;
DROP TABLE RGMS_DB.Groups;

DROP DATABASE RGMS_DB;

CREATE DATABASE RGMS_DB;

CREATE TABLE RGMS_DB.Groups (
	Id INT PRIMARY KEY NOT NULL auto_increment,
	GroupName VARCHAR(100) NOT NULL
);

CREATE TABLE RGMS_DB.Users (
	Id INT PRIMARY KEY NOT NULL auto_increment,
	FirstName VARCHAR(64),
	LastName VARCHAR(64),
	Username VARCHAR(64) NOT NULL UNIQUE,
	Passphrase VARCHAR(64)NOT NULL,
	ImageReference VARCHAR(512),
	GroupId INT NOT NULL REFERENCES RGMS_DB.Groups(Id),
	IsAdmin BOOLEAN DEFAULT 0
);

CREATE TABLE RGMS_DB.Meetings (
	Id INT PRIMARY KEY NOT NULL auto_increment,
	CreatedByUserId INT NOT NULL REFERENCES RGMS_DB.Users(Id),
	DateCreated DATETIME DEFAULT NOW(),
	DateDue DATETIME NULL DEFAULT NOW(), /* NOW() + 1 */
	GroupId INT REFERENCES RGMS_DB.Groups(Id)
);